Title =  "主标题"
LanguageCode = "zh-CN"
BaseUrl = "https://github-young.github.io/hugo-theme-next/"
Theme =  "hugo-theme-next"
#MetaDataFormat =  "toml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  true
HasCJKLanguage = true
PreserveTaxonomyNames = true
UglyUrls = false
DefaultContentLanguage = "zh"

[Params]
  Introduce = "简介"
  Description = "描述"
  Keywords =  "关键词1，关键词2"
  Subtitle = "副标题"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg" # options: false
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  Fancybox = true

[Author]
  Name = "作者"

[Params.Share]
  Baidu = false

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 2
[[Menu.Main]]
  Name = "分类"
  Pre = "folder"
  URL = "/categories/"
  Weight = 3
[[Menu.Main]]
  Name = "标签"
  Pre = "tags"
  URL = "/tags/"
  Weight = 4
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 5

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/github-young/"

# See [Color Schemes](https://xyproto.github.io/splash/docs/)
[markup]
  [markup.highlight]
    lineNos = true
    style = "monokailight"
